services:
  postgres:
    image: postgres:16
    container_name: rdms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: road_distress_db
      POSTGRES_USER: rdms_user
      POSTGRES_PASSWORD: rdms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

