"""add_report_filepath

Revision ID: 5de4c308d694
Revises: d6cc96c83bac
Create Date: 2026-06-22 16:46:39.467192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de4c308d694'
down_revision: Union[str, Sequence[str], None] = 'd6cc96c83bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('filepath', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'filepath')
    # ### end Alembic commands ###
