"""add_maintenance_engine_fields

Revision ID: d6cc96c83bac
Revises: ede64c23ac2d
Create Date: 2026-06-22 16:08:01.358617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cc96c83bac'
down_revision: Union[str, Sequence[str], None] = 'ede64c23ac2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_tasks', sa.Column('estimated_response_time', sa.String(length=100), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('maintenance_category', sa.String(length=100), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('estimated_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_tasks', 'estimated_cost')
    op.drop_column('maintenance_tasks', 'maintenance_category')
    op.drop_column('maintenance_tasks', 'estimated_response_time')
    # ### end Alembic commands ###
