"""add_video_detection_pipeline

Revision ID: ede64c23ac2d
Revises: e87981ce6e5e
Create Date: 2026-06-22 15:57:17.993991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede64c23ac2d'
down_revision: Union[str, Sequence[str], None] = 'e87981ce6e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_distresses', sa.Column('video_id', sa.Integer(), nullable=True))
    op.add_column('road_distresses', sa.Column('frame_number', sa.Integer(), nullable=True))
    op.add_column('road_distresses', sa.Column('video_timestamp', sa.Float(), nullable=True))
    op.add_column('road_distresses', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('road_distresses', sa.Column('detection_image_path', sa.String(length=512), nullable=True))
    op.create_foreign_key(op.f('fk_road_distresses_video_id_uploaded_videos'), 'road_distresses', 'uploaded_videos', ['video_id'], ['id'], ondelete='SET NULL')
    op.add_column('uploaded_videos', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('uploaded_videos', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('uploaded_videos', sa.Column('processing_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_videos', 'processing_duration')
    op.drop_column('uploaded_videos', 'processing_completed_at')
    op.drop_column('uploaded_videos', 'processing_started_at')
    op.drop_constraint(op.f('fk_road_distresses_video_id_uploaded_videos'), 'road_distresses', type_='foreignkey')
    op.drop_column('road_distresses', 'detection_image_path')
    op.drop_column('road_distresses', 'source_type')
    op.drop_column('road_distresses', 'video_timestamp')
    op.drop_column('road_distresses', 'frame_number')
    op.drop_column('road_distresses', 'video_id')
    # ### end Alembic commands ###
